default: &default
  application_name: registration
  dde_server: 127.0.0.1:3002
  dde_username: admin
  dde_password: password
  site_code: MTA
  secure_connection: false
  help_base_url: http://127.0.0.1:3001/

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
